name: Build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{github.secrets.WATCHTOWER_URL}}
          method: 'POST'
          customHeaders: '{ "Authorization" : "Bearer ${{github.secrets.WATCHTOWER_HTTP_API_TOKEN}}" }'
